# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    ports:
    - "127.0.0.1:5432:5432"
    restart: always
    environment:
      PGHOST: '127.0.0.1'
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: smallgroupdb
      POSTGRES_PASSWORD: ${PGPASSWORD}
      TZ: 'EST'
      PGTZ: 'EST'
    volumes:
       - /media/usbdrive/smallgroup/db:/var/lib/postgresql/data